run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gosec
    - goconst
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  gosec:
    excludes:
      - G204

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - typecheck
    - path: internal/infrastructure/repositories/repository_test\.go
      linters:
        - typecheck
    - path: internal/usecases/url_usecase_test\.go
      linters:
        - typecheck
    - path: internal/utils/
      linters:
        - typecheck
