run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - goconst
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
  gosec:
    excludes:
      - G204

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
